import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {AppLayout} from "@/components/layout/AppLayout";
import {ThemeProvider} from "next-themes";
import {Toaster} from "@/components/ui/sonner";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <Toaster richColors position="top-right" />
      <ThemeProvider
          attribute="class" // This tells next-themes to update the class on the <html> tag
          defaultTheme="system" // Can be "light", "dark", or "system"
          enableSystem // Allows respecting the user's OS preference
          disableTransitionOnChange // Prevents theme transitions on page load/hydration
      >
          {children}
      </ThemeProvider>
      </body>
    </html>
  );
}
